### ISSUE TITLE
Добавить поддержку TypeScript в библиотеку.

### ISSUE THREAD

**Issue by EveryDayRains** [NztForum/node-lzt#4]
Если вы уже используйте ES modules, то почему бы проще не было написать библиотеку на TS сразу? Поскольку кодерам на TS не удобно будет, надо будет делать форк и писать тайпинги самому, либо в каждом проекте писать типы под библиотеку чтобы проект компилировался.
Пожалуйста, адаптируйте библиотеку под TS добавив тайпинги либо перепишите на TS и сделайте типы к методам.

**Comment by ne-lanskoy** [comment]
пошел нахуй

**Comment by zaebalo-php** [comment]
пошел НАХУЙ

**Comment by zoto-ff** [comment]
@zaebalo-php вторая личность курла разлогинься
